service: slsA

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: local
  environment:
    QUEUE_URL: http://sqs.us-east-1.172.17.0.1:4566/000000000000/slsB-local-orderQueue
    AWS_ENDPOINT: http://172.17.0.1:4566
    AWS_REGION: us-east-1

plugins:
  - serverless-localstack
  - serverless-offline

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: true
    lambda:
      mountCode: true

  serverless-offline:
    httpPort: 3001
    lambdaPort: 3002
  
  queueName: order-queue

functions:
  createOrder:
    handler: src/handlers/createOrder.handler 
    events:
      - http:
          path: orders
          method: post
 
resources:
  Resources:
    OrderQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}